# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-17 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0154_add_storage_usage_flag'),
        ('osf', '0154_remove_ember_project_registrations_flag'),
    ]

    operations = [
    ]
