# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-29 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0174_add_formblock_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationformblock',
            name='question_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registrationformblock',
            name='block_type',
            field=models.CharField(choices=[(b'short-text-input', b'short-text-input'), (b'long-text-input', b'long-text-input'), (b'singleselect', b'singleselect'), (b'multiselect', b'multiselect'), (b'osf-author-import', b'osf-author-import'), (b'osf-upload', b'osf-upload'), (b'h1', b'h1'), (b'h2', b'h2'), (b'h3', b'h3'), (b'select-input-option', b'select-input-option'), (b'select-input-other', b'select-input-other'), (b'input-label', b'input-label')], db_index=True, max_length=31),
        ),
        migrations.AlterUniqueTogether(
            name='registrationformblock',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='registrationformblock',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='registrationformblock',
            name='page',
        ),
        migrations.RemoveField(
            model_name='registrationformblock',
            name='section',
        ),
        migrations.RemoveField(
            model_name='registrationformblock',
            name='size',
        ),
    ]
