# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-08 19:42
from __future__ import unicode_literals

from django.db import migrations
import osf.utils.datetime_aware_jsonfield
from osf.utils.migrations import build_flattened_jsonschema


def clear_registration_responses_jsonschema(state, schema):
    RegistrationSchema = state.get_model('osf', 'registrationschema')
    RegistrationSchema.objects.update(registration_responses_jsonschema={})


def migrate_registration_responses_jsonschema(state, schema):
    RegistrationSchema = state.get_model('osf', 'registrationschema')
    for schema in RegistrationSchema.objects.all():
        schema.registration_responses_jsonschema = build_flattened_jsonschema(schema)
        schema.save()


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0185_migrate_registered_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationschema',
            name='registration_responses_jsonschema',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.RunPython(migrate_registration_responses_jsonschema, clear_registration_responses_jsonschema),
    ]
