# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-08 19:42
from __future__ import unicode_literals

from django.db import migrations
from osf.utils.migrations import build_flattened_jsonschema


def clear_registration_responses_jsonschema(state, schema):
    RegistrationSchema = state.get_model('osf', 'registrationschema')
    RegistrationSchema.objects.update(registration_responses_jsonschema={})


def migrate_registration_responses_jsonschema(state, schema):
    RegistrationSchema = state.get_model('osf', 'registrationschema')
    for schema in RegistrationSchema.objects.all():
        schema.registration_responses_jsonschema = build_flattened_jsonschema(schema)
        schema.save()


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0189_migrate_registered_meta'),
    ]

    operations = [
        migrations.RunPython(migrate_registration_responses_jsonschema, clear_registration_responses_jsonschema),
    ]
