# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0006_wikipage_wikiversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikiversion',
            name='_id',
        ),
    ]
