# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0006_wikipage_wikiversion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wikiversion',
            old_name='creator',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='wikiversion',
            old_name='wiki',
            new_name='wiki_page',
        ),
        migrations.RemoveField(
            model_name='wikipage',
            name='content',
        ),
        migrations.AddField(
            model_name='wikiversion',
            name='content',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
