# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0007_auto_20171220_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiversion',
            name='wiki_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='addons_wiki.WikiPage'),
        ),
    ]
