# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0007_remove_wikiversion__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='wikiversion',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
