# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0008_auto_20171220_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiversion',
            name='identifier',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
