# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0008_auto_20171227_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='wiki_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
