# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0009_wikiversion_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wikis', to='osf.AbstractNode'),
        ),
    ]
