# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0010_auto_20171220_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiversion',
            name='content_type_pk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
