# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0010_auto_20180104_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikipage',
            name='wiki_key',
        ),
        migrations.RemoveField(
            model_name='wikiversion',
            name='is_deleted',
        ),
    ]
