# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 15:49
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0011_wikiversion_content_type_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiversion',
            name='date',
            field=osf.utils.fields.NonNaiveDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
