# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import osf.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0011_auto_20180105_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikiversion',
            name='content_type_pk',
        ),
        migrations.AddField(
            model_name='wikiversion',
            name='_id',
            field=models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True),
        ),
    ]
